export const store = {
  apiBase: null,
  apiV1: null,
  units: [],
  selectedScope: 'nacional',
  selectedDepartment: null,
  selectedUnitId: null,
  customGeojson: null,
  map: null,
  chart: null,
  currentLayer: 'alerta',
  activeTileLayer: null,
  layerInstances: {},
  availableOverlays: [],
  activeLayers: ['alerta'],
  layerOpacities: {},
  layerErrors: {},
  layerMenuOpen: false,
  timelineDate: null,
  timelineWindowDays: 365,
  timelinePlaying: false,
  timelineSpeed: 1,
  timelineFrames: null,
  timelineLoading: false,
  timelineEnabled: false,
  timelineBuffering: false,
  timelineManifestKey: null,
  timelineContext: null,
  timelineContextLoading: false,
  timelineContextRequestSeq: 0,
  timelineForecastCollapsed: false,
  // Fase 3 Field Mode: timeline propio del campo.
  fieldTimelineFrames: [],
  fieldTimelineSource: 'global',  // 'global' | 'field'
  fieldTimelineDate: null,
  timelineEvents: [],
  timelineEventsLoading: false,
  timelineEventsKey: null,
  preloadVisible: true,
  preloadMiniVisible: false,
  preloadRunKey: null,
  preloadStatus: null,
  preloadProgress: 0,
  preloadCriticalReady: false,
  preloadViewportSignature: null,
  timelineWarmSignature: null,
  onTimelineDateChange: null,
  onMapLayerChange: null,
  baseTileLayer: null,
  unitMarkers: [],
  focusMarker: null,
  departmentsLayer: null,
  departmentsLookup: {},
  sectionsLayer: null,
  sectionsLookup: {},
  productiveLayer: null,
  productiveLookup: {},
  hexLayer: null,
  hexLookup: {},
  farmGuideLayer: null,
  farmFieldsLayer: null,
  farmFieldsLookup: {},
  farmFieldLabelsLayer: null,
  farmFieldLabelPositions: {},
  farmPaddocksLayer: null,
  farmPaddocksLookup: {},
  farmPaddockLabelsLayer: null,
  farmPaddockLabelPositions: {},
  farmDraftLayer: null,
  farmDraftType: null,
  farmEditorActive: false,
  farmDraftChangeHandler: null,
  farmDraftCreateHandler: null,
  selectedProductiveId: null,
  selectedSectionId: null,
  selectedHexId: null,
  selectedFieldId: null,
  selectedPaddockId: null,
  onPolygonDraw: null,
  sidebarView: 'monitor',
  settingsSchema: null,
  settingsPayload: null,
  settingsAudit: [],
  settingsMode: 'global',
  settingsCoverageClass: 'pastura_cultivo',
  settingsDraft: null,
  profileSchema: null,
  profilePayload: null,
  profileDraft: null,
  profileStatus: null,
  currentModel: null,
  weatherFilterValue: 'current',
  weatherFilterOptions: [],
  weatherModel: null,
  farmOptions: null,
  farmEstablishments: [],
  farmFields: [],
  selectedEstablishmentId: null,
  selectedFieldDetail: null,
  selectedPadronSearch: null,
  fieldDraftGeometry: null,
  paddockDraftGeometry: null,
  authUser: null,
  authCsrfToken: null,
  authSession: null,
  authReady: false,
  // Bloqueo transitorio de cambios de viewport tras una selección admin (depto/sección).
  // Mientras true, highlightDepartment/highlightSection/updateFocus/fitLayerBounds y demás
  // caminos de preload/timeline NO deben ejecutar setView ni fitBounds.
  preserveViewportTransient: false,
  // Clipping multi-nivel
  clipScope: 'nacional',
  clipRef: null,
  clipMaskLayer: null,
  scopeGeometryCache: new Map(),
};

export function setStore(patch) {
  Object.assign(store, patch);
  return store;
}
