export const store = {
  apiBase: null,
  apiV1: null,
  units: [],
  selectedScope: 'nacional',
  selectedDepartment: null,
  selectedUnitId: null,
  customGeojson: null,
  map: null,
  chart: null,
  currentLayer: 'alerta',
  activeTileLayer: null,
  baseTileLayer: null,
  unitMarkers: [],
  focusMarker: null,
  departmentsLayer: null,
  departmentsLookup: {},
  sectionsLayer: null,
  sectionsLookup: {},
  productiveLayer: null,
  productiveLookup: {},
  hexLayer: null,
  hexLookup: {},
  selectedProductiveId: null,
  selectedSectionId: null,
  selectedHexId: null,
  onPolygonDraw: null,
  sidebarView: 'monitor',
  settingsSchema: null,
  settingsPayload: null,
  settingsAudit: [],
  settingsMode: 'global',
  settingsCoverageClass: 'pastura_cultivo',
  settingsDraft: null,
  profileSchema: null,
  profilePayload: null,
  profileDraft: null,
  profileStatus: null,
  currentModel: null,
  weatherFilterValue: 'current',
  weatherFilterOptions: [],
  weatherModel: null,
  authUser: null,
  authCsrfToken: null,
  authSession: null,
  authReady: false,
};

export function setStore(patch) {
  Object.assign(store, patch);
  return store;
}
